import '../globals.scss'
import Link from "next/link";
import {getPages} from "@/sanity/sanity-utils";

export const metadata = {
    title: 'Next + Sanity',
    description: 'Generated by create next app',

}

export default async function RootLayout({children}) {

    const pages = await getPages();
    return (
        <html lang="en">
        <body>
        <header>
            <Link href="/">Home</Link>
            <>
                {pages.map((page) => (
                    <Link href={`/${page.slug}`} key={page._id}>
                        {page.title}
                    </Link>
                ))}
            </>

        </header>

        <main>{children}</main>

        </body>
        </html>
    )
}
