import '../globals.scss'
import Link from "next/link";
import {getPages} from "@/sanity/sanity-utils";
import NavBar from "@/app/(site)/components/NavBar";

export const metadata = {
    title: 'Next + Sanity',
    description: 'Generated by create next app',

}

export default async function RootLayout({children}) {

    return (
        <html lang="en">
        <body>
        <NavBar/>

        <main>{children}</main>

        </body>
        </html>
    )
}
